---
- name: Deploy Flask Application
  hosts: web_servers
  become: yes
  
  vars:
    app_name: flask_app
    app_user: flask
    app_group: flask
    app_directory: /opt/flask_app
    venv_path: "{{ app_directory }}/venv"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - ufw
        state: present

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '80'
        - '443'
        - '5000'

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Setup Python virtual environment
      command:
        cmd: python3 -m venv "{{ venv_path }}"
        creates: "{{ venv_path }}"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_directory }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Kill existing Flask processes
      shell: pkill -f "python -m flask run" || true
      ignore_errors: yes

    - name: Start Flask application
      shell: |
        cd {{ app_directory }}
        source {{ venv_path }}/bin/activate
        nohup python -m flask run --host=0.0.0.0 > {{ app_directory }}/flask.log 2>&1 &
      become_user: "{{ app_user }}"

    - name: Wait for application to start
      wait_for:
        port: 5000
        timeout: 30

    - name: Check application status
      uri:
        url: http://localhost:5000
        return_content: yes
      register: app_status
      ignore_errors: yes

    - name: Display application log if startup failed
      command: cat {{ app_directory }}/flask.log
      when: app_status.failed is defined
      ignore_errors: yes
