---
- name: Deploy Flask Application
  hosts: web_servers
  become: yes
  
  vars:
    app_name: flask_app
    app_user: flask
    app_group: flask
    app_directory: /opt/flask_app
    venv_path: "{{ app_directory }}/venv"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - ufw
        state: present

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '80'
        - '443'
        - '5000'

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        createhome: yes
        home: "{{ app_directory }}"

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Setup Python virtual environment
      command:
        cmd: python3 -m venv "{{ venv_path }}"
        creates: "{{ venv_path }}"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_directory }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Configure Gunicorn service
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/{{ app_name }}.service
        mode: '0644'

    - name: Start and enable Gunicorn service
      systemd:
        name: "{{ app_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
      notify: restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}
        dest: /etc/nginx/sites-enabled/{{ app_name }}
        state: link
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
